version: '3.1'

services:
  postgres:
    container_name: postgre-dokcer
    image: postgres
    #自動重新啟動
    restart: always
    ports:
      - 5433:5433
    environment:
      #預設使用者
      POSTGRES_USER: postgres
      #預設密碼
      POSTGRES_PASSWORD: postgres
      #預設資料庫
      POSTGRES_DB: postgreDokcer
      #將資料掛載到電腦中、刪除容器時資料還會保留
      PGDATA: ./pgdata:/var/lib/postgresql/data/pgdata
